# Generated by Django 3.1.14 on 2022-04-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('jp_name', models.CharField(max_length=100)),
                ('desctiption', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('appeared_at', models.DateTimeField()),
                ('disappeared_at', models.DateTimeField()),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=1)),
                ('defence', models.IntegerField(default=1)),
                ('stamina', models.IntegerField(default=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokemon_entities.pokemon')),
            ],
        ),
    ]
