# Generated by Django 3.1.14 on 2022-04-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='desctiption',
            new_name='description',
        ),
    ]
