# Generated by Django 3.1.14 on 2022-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20220420_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='nopic.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
